### ISSUE TITLE
Audio isn't playing

### ISSUE THREAD

**Issue by Temp-insta** [santosharron/Music-Visualizer#1]
I had cloned this repo and added my audio source file, but it's not playing anyways to fix it?

**Comment by santosharron** [comment]
Due to Chrome's autoplay policy, audio does not play when clicking the screen. A fix I use for this is to run Live Server on VSCode for this project, change something in the code and undo the change for the project to refresh. The audio plays now :D
Perhaps using this method to enable audio playback isn't ideal, but I wanted to keep things clean for this project (I didn't want to have a lot of buttons around), so I resorted to this method. I'm closing this issue. I'll reopen this issue if you're getting the same error comment below.
